global:
  scrape_interval: 10s
  scrape_timeout: 5s

rule_files:
  - alert.yml

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'alertmanager:9093' ]

scrape_configs:
  - job_name: services
    metrics_path: /q/metrics
    static_configs:
      - targets:
          - 'iexists:8080'
          - 'idonotexists:564'


